language: node_js
node_js:
- 6.9.5
notifications:
  email: false
  webhooks: https://ambrosio-tele.herokuapp.com/sacarinobot/travisci/133188453
  on_success: always
  on_failure: always
  on_start: always
before_script:
- npm install -g grunt-cli
deploy:
  api_key: 
    secure: AKi9sT33gokf4ERhjDNZY+IJ10SQfDXaCO3kn+jsFIXJ6n4EAZ46rkByKhAN26u4sRPKG0B2PzCalm6hd2wHnwMDqN3bpC1XYwih/lvCbR2IF7mQmjZ1WML0dXY1rdAB1yXAFvZRqBv+ddBevHojlKS4Sqm4A2wXpxuOD/w9atzHwJNu4lylOvRV2V+jGItHW/yXV61xq0A/wS40EACHHr+bAYUqAyrg7SiCYm3XlwO5oYuZFl/FG/jZOw4ZqyqHrkzREbMS7F9HeSIA1Pn7AAZQC8I4UvXJ0mRf4PQ4AWsIgkKz7eD7vZvCk8F7FVbNM9U7Hfsp0lqxAGOe65ilh/DvQ+JJsfBmMohPllY5M5YrPKsWsSLEL5V1fIPvthLGIcxloLia/feFVMzAxnDJZMQVbHcince9/y7xqNMDTlZqEsHfSugE9xudgX6vUzt9OT82sAHTICuLvtDAKbi5RKPiMWtX1VNpeCcgIWiE0Umu+2+n5FixwkP3bJw//WfzWVBGRSWgyhAubuM/YdkEGai2pJAg2jxLoVCU9cjf0hWgiK59bpBqKKmiYMs5yzep8dvsdFzkKSWwIAbDldc9L43mKtEygiGuH6UGsJtAPg0iqhdz1zTNfpCc+4v7lsDRJRBBQizUa+k0ggMHAm00bSe1xgTH1aPN26g7hjcL+jA=
  email: 
    secure: tCRrGp2p1zmkyGvjskjvkNIMMHsq8HPBDvdXDtvqnqOOoobFZpVCMMcX7b7AffMzDRKSYHEcxGNSYHI8nrQZC5NlhhzuBc5+H8kdoGNyyCcIbeK0bP5yRnA1Nk3xP/34NCvmewYps8crAvCI3AQLM/Jsv2rNmiIm0hSABeer1wbjxAFld0jTWMtgzYoCnSyxIcOutkHZIFW/KT+1Izv81u5EEukWgE5rJSubwFx05cv0LfVJaRW4XWA+0eHlHbHn24yM2fF4hrW+PZZugGiCrabOREX76Ag4ICSozIOU2ODbjxifvAVhfymbj6bXcisTlLfQVzGSMFmntEyD9J/CRkJU7eOKdq67cH5kUZR1iYZ6KEFpIfdZst8KhdlMnlFvG7vB78dGn2ZsHTuM8qq1UNHiA8unXD1lSDewOWoyfpWc0mAn+H0qoRz3DVP+pQ04Viwl3K0H2bPGwkDWM1dZAaictxZVKdfJ+7crax+XCvpnOj1aeE2nEcViW5v5wbdFRcK+PcsrJhez8QRmMusEMWyVqOPUwiri07X9f87zmOReYGDwq+aB+HDmq13V4vrO1QnsIGzghBvdEDMJ8LMZMq6PacthVy38qyJDAt+deXygHulsi8zUW1lhjxORpJ7PQpum7WPzWKBIQMoQsJih4TCD3kggeSI8z5Pdl3GpLxI=
  provider: npm
